-- hydra-shell's Hyprland entrypoint (Lua config, Hyprland 0.55+).
--
-- Installed by the Setup Wizard (Modules/Panels/SetupWizard/SetupHyprlandStep.qml)
-- to ~/.config/hypr/hyprland.lua. Load order below is deliberate and mirrors
-- the layering documented in PLANO_INTEGRACAO_HYPRMOD.md §1/§4.5:
--
--   modules/*.lua           <- hydra-shell defaults (this repo, versioned, never
--                               hand-edited; safe to overwrite on update)
--   hydra-shell/settings.lua <- generated by the Settings panel (Hyprland tab);
--                               only the options you changed, regenerated on
--                               every Save. Wins over the modules above.
--   hydra-shell/rebinds.lua  <- generated by the Settings panel (Keybinds
--                               sub-tab); remaps shipped keybinds without
--                               touching modules/binds.lua.
--   user.lua                 <- yours. Seeded once, never touched again by
--                               the Settings panel or by updates. Wins over
--                               everything above it.
--
-- optional(): probe with package.searchpath before requiring, then pcall the
-- require. A missing drop-in (a fresh install with no hydra-shell/settings.lua
-- yet, or no user.lua) must never surface Hyprland's "Your config has errors"
-- overlay; a drop-in that exists but fails to parse must never fail silently
-- either, so we print (not swallow) that error. Pattern proven in production
-- by ryoku-arch (ryoku/hyprland/hyprland.lua).
local function optional(mod)
  if package.searchpath == nil or package.searchpath(mod, package.path) then
    local ok, err = pcall(require, mod)
    if not ok then
      print("hydra-shell: config module '" .. mod .. "' failed to load: " .. tostring(err))
    end
  end
end

-- Shipped defaults. Never edited by the Settings panel or by hand — take
-- ownership of a module by copying it into user.lua and overriding there
-- instead (see user.lua.example).
require("modules.programs")
require("modules.env")
require("modules.input")
require("modules.decoration")
require("modules.animations")
require("modules.window_rules")
require("modules.binds")
require("modules.autostart")

-- hydra-shell/monitors.lua is generated by Display -> MonitorLayoutSubTab
-- (Services/Hardware/MonitorService.qml's saveToHyprlandConfig(), via
-- HyprlandLuaWriter.writeMonitors()) — separate from the Hyprland Settings
-- tab's own hydra-shell/settings.lua on purpose: monitor layout has its own
-- save button and its own live-apply path (hl.monitor(...) per output,
-- Modules/.../MonitorLayout/backends/HyprlandBackend.js), independent of the
-- rest of the Hyprland tab's draft/save cycle.
optional("hydra-shell.monitors")

-- hydra-shell/settings.lua issues hl.config/hl.window_rule/hl.bind/... calls
-- directly (same shape as modules/*.lua) — it is generated fresh on every
-- Save by HyprlandLuaGen.js, so there is nothing to keep in sync here beyond
-- requiring it.
optional("hydra-shell.settings")
optional("hydra-shell.rebinds")

-- Color template output (window border / group bar colors) is unrelated to
-- this plan and manages its own inclusion: Scripts/bash/template-apply.sh
-- idempotently appends a `dofile(...)` line for
-- ~/.config/hypr/hydra/hydra-colors.lua at the end of whichever file is
-- ~/.config/hypr/hyprland.lua the first time a Hyprland color template runs —
-- this file included. Nothing to add here; do not hand-add a second include.

-- Last word. Yours.
optional("user")
