[Metadata]
Name=Hydra
Version=1
Author=Hydra Shell
Description=Dynamic Material colors from Hydra Shell

[InputPanel]
NormalColor={{colors.on_surface.default.hex}}
HighlightColor={{colors.on_primary.default.hex}}
HighlightBackgroundColor={{colors.primary.default.hex}}
HighlightCandidateColor={{colors.on_primary.default.hex}}
FullWidthHighlight=True

[InputPanel/Background]
Color={{colors.surface_container.default.hex}}
BorderColor={{colors.outline_variant.default.hex}}
BorderWidth=1

[InputPanel/Background/Margin]
Left=4
Right=4
Top=4
Bottom=4

[InputPanel/Highlight]
Color={{colors.primary.default.hex}}

[InputPanel/Highlight/Margin]
Left=6
Right=6
Top=4
Bottom=4

[InputPanel/TextMargin]
Left=10
Right=10
Top=6
Bottom=6

[Menu]
NormalColor={{colors.on_surface.default.hex}}
HighlightCandidateColor={{colors.on_primary.default.hex}}
Spacing=4

[Menu/Background]
Color={{colors.surface_container_high.default.hex}}
BorderColor={{colors.outline_variant.default.hex}}
BorderWidth=1

[Menu/Background/Margin]
Left=4
Right=4
Top=4
Bottom=4

[Menu/Highlight]
Color={{colors.primary.default.hex}}

[Menu/Highlight/Margin]
Left=6
Right=6
Top=4
Bottom=4

[Menu/Separator]
Color={{colors.outline_variant.default.hex}}

[Menu/TextMargin]
Left=10
Right=10
Top=6
Bottom=6
